USE stagingDB;
CREATE TABLE IF NOT EXISTS staging_movies (
	movieId INT NOT NULL, 
	title VARCHAR(255) NOT NULL,
	year SMALLINT DEFAULT NULL,
	genres VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4;